### PR TITLE
cplusplus_basics chapter cleanup 1

### PR DESCRIPTION
**Pull request by synesthete**
Starting a read of the book and thought I would contribute fixes for errors I came across.

### CODE REVIEW

**Comment by mikewesthad** [comment]
@synesthete thanks much!  You've got some edits for two authors in here - pinging @roymacdonald and @jtnimoy to merge this.  

If you happen to have fixes for other chapters, would you mind submitting them as separate pull requests?  That would let each author independently approve the incoming edits for (only) their chapter.

**Comment by synesthete** [comment]
@mikewesthad Certainly. Seems I inadvertently shoved subsequent commits into this same pull request.

**Comment by mikewesthad** [comment]
Much appreciated!

**Comment by synesthete** [comment]
Would it make sense to revert the commit on the setup_and_project_structure chapter? I can then get a new branch and pull request going for it. Hoping to make the least amount of work for all involved.

**Comment by mikewesthad** [comment]
I wouldn't worry about it for this pull request.  These are all small fixes that @roymacdonald and @jtnimoy should be able to eyeball quickly then merge.

**Comment by roymacdonald** [comment]
Hey @synesthete thanks for all those fixes.
I'll merge my chapter right now.
Best!

**Comment by ofZach** [comment]
@jtnimoy these seems like good changes, can you look at them?

**Comment by jtnimoy** [comment]
I'm happy with all the changes and grateful to Synesthete for proof reading!

**Comment by jtnimoy** [comment]
ok, i just did a merge (by clicking that link on this page that says "use the command line") and the file `chapters/cplusplus_basics/chapter.md` will auto-merge with no complaints. So after @roymacdonald does his manual merge, it should all fall into place.

**Comment by mikewesthad** [comment]
I believe the merge conflict was because I made a recent commit to add links to @roymacdonald's chapter.  Since you both approved the changes, I figured I should just fix it and merge myself

**Comment by roymacdonald** [comment]
Hey Michael, I saw that you added those links. Thanx! Were you able to fix
the merge?
best

*Roy Macdonald*
+569 8248 8478

**Comment by mikewesthad** [comment]
No problem.  I had started going through the first few chapters making sure that oF docs were linked.  Didn't get very far though.

Yep - it's all merged.

**Pull request merged**
