### PR TITLE
Added python 3 compatible build scripts

### PR DESCRIPTION
**Pull request by baskeboler**
Created `scripts/createPDFBook.py3` and `scripts/createWebBook.py3` which may be run with python 3.

### CODE REVIEW

**Comment by bilderbuchi** [comment]
I think it would be preferable to modify the existing scripts so they run on both versions - the code is not that complicated. `from __future__ import ...` and, if necessary, http://python-future.org/ Stage 1 changes are your friend. 
What are the changes that you had to make?

**Comment by baskeboler** [comment]
you're right. I did not want to break anything for the python2 people. I reviewed my changes and there is some unnecessary garbage. I just started off from a fresh copy of createWebBook.py and the minimun changes I had to make for it to finish the build were:
* to change the print statements to function form
* change `open(destChapterPath)` and similiars to `open(destChapterPath, "rb")`
* replace `html = str(soup)` with `html = soup.encode()`

I am not sure if these changes work under python 2. Let me know and I'll create a new pull request.

**Comment by bilderbuchi** [comment]
> to change the print statements to function form

this is taken care of by `from __future__ import print_function` and using the `print(x)` form everywhere.

> change open(destChapterPath) and similiars to open(destChapterPath, "rb")

I'm unsure if this has to be read as a binary file. Quickly looking through the code, there's a wide variety of binary and text reads/writes around. @arturoc any input here?

>  replace html = str(soup) with html = soup.encode()

that is  also a problem of the binary/unicode python3 transition. encode turns a unicode string into bytes (which you need if you opened your file in binary mode, see above). I have a feeling this should work in py2, too, if you also changed the file stream object mode to binary.

**Comment by arturoc** [comment]
no idea, i haven't looked much at the book code. usually using binary is safe though, it usually only means don't convert breaklines in windows

**Pull request closed without merging**
