### PR TITLE
Master

### PR DESCRIPTION
**Pull request by fdiba**
ofPtr is deprecated

### CODE REVIEW

**Comment by bilderbuchi** [comment]
@fdiba I don't know what you did or want to do, but this PR does not look correct.

**Comment by bilderbuchi** [comment]
OK, as there's #216 now, I'll just close this.

**Comment by fdiba** [comment]
Sorry It was my first attempt to achieve my first pull request.

**Comment by bilderbuchi** [comment]
yeah, no problem. :-)

**Pull request closed without merging**
