### PR TITLE
revised Cplusplus basics

### PR DESCRIPTION
**Pull request by tpltnt**
Hi,

i went through the "C++ basics" chapter and fixed a few issues along the way.
Cheers,
tpltnt

### CODE REVIEW

**Comment by tpltnt** [comment]
Hey @jtnimoy ,
do you think my changes are ok?

**Comment by tpltnt** [comment]
ping @jtnimoy

**Comment by jtnimoy** [comment]
@tpltnt most of it looks great, thanks for taking care of it. Was there a book-wide decision to start putting ... inside all our ()?

**Comment by tpltnt** [comment]
Not into all of them, only when the function takes one or more parameters. It is documented in the [editors guide](https://github.com/openframeworks/ofBook/blob/master/info/editorsGuide.md#variables-functions-and-functions-with-arguments).

**Comment by tpltnt** [comment]
@jtnimoy are you signing off on my changes then? Please merge in that case.

**Comment by tpltnt** [comment]
Thank you for merging.

**Pull request merged**
