### PR TITLE
Setup and project structure fixes

### PR DESCRIPTION
**Pull request by tpltnt**
I went through the draft and fixed issues along the way. Maybe @roymacdonald approves.
Cheers,
tpltnt

### CODE REVIEW

**Comment by ofZach** [comment]
thanks so much for these changes !!!!!

**Comment by roymacdonald** [comment]
@tpltnt, Awesome! much thanks.
You added an editors note, that reads "Who is the 'we' that is talked about in this chapter?"
I think that this "we" is for "we who are writing this book". "we" as a community rather than me as the particular person that began writing this chapter, which so far has been modified by several others. Did this became something confusing while reading?
I really appreciate your editing work. thanks again.
best

**Comment by tpltnt** [comment]
@roymacdonald thank you for the clarification. I added a line explaining it to the chapter.

**Comment by tpltnt** [comment]
@mikewesthad could you pull these changes in?

**Comment by roymacdonald** [comment]
@tpltnt merged. Thanks!!

**Pull request merged**
