### PR TITLE
Added chapter about events

### PR DESCRIPTION
**Pull request by roymacdonald**
I just wrote a chapter about using ofEvents.

It needs some review and finishing a few sections but the core of it is written.
As it is not ready I didn't push directly to the master.

Any feedback is very welcome :)

Cheers!

@arturoc @ofZach @bakercp

### CODE REVIEW

**Comment by roymacdonald** [comment]
Hi @arturoc, I just saw that you post in the OF blog. I was just wondering what I should do with this chapter I wrote, so I could become an official chapter. Should I ditch the old implementation (ofAddListener () ) and only leave the newer one? should I make any mention to the rule of 5 or 3 (with the new implementation it seems that I shouldn´t need it)

**Comment by edap** [comment]
@arturoc @roymacdonald Did you guys come to a conclusion? does it make sense to make a shorter version of this chapter?

**Comment by roymacdonald** [comment]
hey @edap , Nope, we have not agreed on what to do. Its been more than a year since I last read this chapter. I will go through it and update it. 
cheers

**Comment by chilina** [comment]
Hey @roymacdonald, nice job on this chapter I'd love to see it become part of ofBook.  You've put a lot of work into it, and ofEvents have been kinda complex (at least for me).  I'd vote for the following when you get a chance to update it:
1). focus on the new implementation, but you could keep the "old way" too for legacy and context
2). mention the Rule of 3 or 5, because this is why the new implementation is so awesome
3). go into a bit more detail on the lambdas, and how they can be useful and help with customizing listeners (kinda like I started to do in the forum post recently)
4). if there's a way to put ofEventListeners into a container, I'd vote for a discussion on that too.  I've been trying all morning to do it, including with std::move, but the ofEventListener gets destroyed (?) once it leaves the original object.  I haven't tried a vector of pointers yet though.  Maybe the listeners need a class, and the class goes into the container, kinda like @arturoc did in the blog post.

**Comment by roymacdonald** [comment]
Hi @chilina,
thanks for you feedback. This chapter is a bit outdated, as I wrote it when the ofEventListener was still in development and was only available through the github master. I will try to give it a second pass and merge it with arturo's blog post. 
You can put objects that have listeners in a container using a pointer, actually a smart pointer (std::shared_ptr) is much better as you dont need to manage its destruction.
I'll take into account your suggestions.
cheers

**Comment by roymacdonald** [comment]
I made some changes to my github repo that made this PR get automatically closed.
Just as a reference for anyone looking for it, the chapter is now [here](https://github.com/roymacdonald/ofBook/blob/events/chapters/events/chapter.md)

**Pull request closed without merging**
