### PR TITLE
Spelling, readability, packages->packets, etc.

### PR DESCRIPTION
**Pull request by bakercp**
@arturoc Check it.  Thanks!

### CODE REVIEW

**Comment by arturoc** [comment]
thanks! can you add yourself in the credits of the chapter as corrections by... + your website or whatever you prefer?

**Comment by tpltnt** [comment]
Hi @bakercp
i am currently also working on this chapter. Please do a lot of little commits as suggested by the [git best practises](https://sethrobertson.github.io/GitBestPractices/), because right now i have to tear apart your commit and resolve every conflict by hand. A lot of little commit make it way easier to avoid this merge hell.

**Comment by bilderbuchi** [comment]
I think a +26/-28 line-size diff is perfectly reasonable for a commit. Commits should also follow logical boundaries, not primarily changed-word-count limits.
Also, I don't see how, say, a commit for every single line would help you merge it in, as the same number of lines will conflict with your branch. The only helpful thing is that you have dozens of conflict resolution sessions instead of one, but the overall number of conflict markers will stay the same.

**Comment by tpltnt** [comment]
The size of the diff is not an issue. The problem is that by making all changes in one commit you basically make [cherry picking](https://git-scm.herokuapp.com/docs/git-cherry-pick) impossible. A lot of tiny changes are easier to merge (conceptually) than a big one since you do not have to search large blocks of texts for (often tiny) differences. The number of conflicts may stay the same, but resolving them gets way easier.

**Comment by bakercp** [comment]
Hi @tpltnt @bilderbuchi sorry for the commit mayhem.  It's a little tricky to edit a book in this way because most of the paragraphs are a single line, thus git isn't optimized to auto-merge long free-form prose.  For normal code, multiple commits certainly makes sense, but I think for writing projects merging will always take a lot of work as @bilderbuchi suggests.

Anyway, this kind of collaborative writing would probably best be carried out in a real-time collaborative editor / hackpad / google doc / etc. but in the future I'll ping the ofBook list.

**Comment by tpltnt** [comment]
@bakercp you are probably right.

**Comment by bakercp** [comment]
@tpltnt by the way-- thanks for all of your hard work especially in the last few weeks pushing this project along!  It's very much appreciated.

**Pull request merged**
