### PR TITLE
Foreword fixes

### PR DESCRIPTION
**Pull request by tpltnt**
Hi,

i went through the foreword and fixed a few things (mostly spelling). This is probably up to @ofZach to decide since he is the original author.
Cheers,
tpltnt

### CODE REVIEW

**Comment by tpltnt** [comment]
@ofZach can you acknowledge this pull request to that the repository owners are confident in merging it? (I do not want a deadlock here were everyone is waiting for a move of the other). Thank you.

**Comment by ofZach** [comment]
sorry !!  pulling this in....  looks great.  I've personally never used oF (it seems kind of typographically wrong to me!  it's my OCD in action) but I guess this is a super common convention so happy to use it here. 

again, thanks *so* much for this help!

**Comment by tpltnt** [comment]
@mikewesthad could you pull it in?

**Comment by mikewesthad** [comment]
Since @ofZach approved it - sure thing

**Pull request merged**
