### PR TITLE
Updated setup and project structure chapter:

### PR DESCRIPTION
**Pull request by roymacdonald**
- Updated the available IDEs and just point to the corresponding online setup guide instead of having an explanation in this chapter. This should be better for future updates.
- Added a lot of links to the documentation.
- Some other corrections so the whole chapter makes sense.
- Removed mentions to Code::Blocks
- Added QtCreator screenshot

Should fix issue https://github.com/openframeworks/ofBook/issues/297

### CODE REVIEW

**Comment by hamoid** [comment]
Looks good :) But maybe you meant to use backticks instead of single quotes for file names and such? `ball.h` vs 'ball.h'

**Comment by roymacdonald** [comment]
Hi @hamoid ,
I just copied what was there. It seems that there's some inconsistency in that chapter at the moment of referring to files names. I am not sure if there's any guideline about this in the whole book.

**Comment by hamoid** [comment]
Hi @roymacdonald ,
I see! I looked in other chapters and there seems to be many approaches. Files as normal text, cursive, with single quotes, double quotes, italics and code formatted. Maybe use **bold** here? Just joking :) Normalizing this sounds like a big task.

**Comment by roymacdonald** [comment]
Just changed to backticks. Thanks for pointing out.

cheers.

**Comment by edap** [comment]
it looks good to me too

**Pull request merged**
