### PR TITLE
python 2/3 compatible build scripts

### PR DESCRIPTION
**Pull request by baskeboler**
Taking http://python-future.org/compatible_idioms.html into consideration, modified createWebBook.py and createPDFBook.py to make them python 2/3 compatible. Ran futurize stage 1 mode on both scripts and slightly modified file IO.

### CODE REVIEW

**Comment by bilderbuchi** [comment]
looks good, thanks! did you test on both py2 and py3 to see if it runs correctly?

pinging @arturoc for review.

**Comment by baskeboler** [comment]
yes, tested it with python 2.7 and 3.4 on windows.

**Comment by bilderbuchi** [comment]
great, thanks! :+1:

**Comment by arturoc** [comment]
just tested it and it's working great, thanks!

**Comment by baskeboler** [comment]
awesome!

**Pull request merged**
