### PR TITLE
Markdown fixes (Headers now render correctly on github)

### PR DESCRIPTION
**Pull request by bakercp**
View non-whitespace changes with:

https://github.com/openframeworks/ofBook/pull/261/files?w=1

TL;DR

Headings now need a space after the # to be parsed correctly.

See:

https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown
https://githubengineering.com/a-formal-spec-for-github-markdown/

### CODE REVIEW

**Comment by bakercp** [comment]
After working on this for a bit, I ended up with this regex (in atom.io flavor)

find:
`^(#{1,})(?! |#|include|pragma|if|endif|define|version|import|\!)`

replace
`$1 `

**Comment by bakercp** [comment]
@mikewesthad could you take a look at this?

**Comment by bakercp** [comment]
Super.  I was using atom's remark linter for some extra help.

Cool, I got some other ofbook fixes etc on the way now that that stuff is fixed :)

**Comment by mikewesthad** [comment]
Ah, nice. Yeah, feel free to ping me if you need a set of eyes on a PR.

**Pull request merged**
