### PR TITLE
Fix typo: soime > some

### PR DESCRIPTION
**Pull request by hamoid**

### CODE REVIEW

**Comment by arturoc** [comment]
thanks!

**Comment by hamoid** [comment]
Oops I hope I didn't break anything. I sent you an e-mail about the "Fix typos" commit, which was not meant to be pulled in. I ran the file through an external spellchecker, and I think something went wrong in the process, because ".svg" disappeared from the image links. I also see other changes I did not do myself. Could you make sure it's alright? (or revert and I do it properly).

**Comment by arturoc** [comment]
ah ok, i think everything is fine except for the svgs do you want to send another PR fixing that?

**Comment by hamoid** [comment]
Sure, I'll do that

**Comment by hamoid** [comment]
Done

**Pull request merged**
