### PR TITLE
Edits for Memory Chapter

### PR DESCRIPTION
**Pull request by brannondorsey**
Hey @arturo, here are my edits for your Memory chapter. Again, most of my edits are inline/**[BD: noted]**. The only other thing that I will say is that I did not change variableNames to `variableNames` in the text, but I think that this is advised. I can go back over the chapter and do that for you if you'd like, but I thought I should mention it first. Also, I made no attempt to standardize the we/you language but I suggest that one is picked. Other than that the chapter is quite solid. I think it is the most finished (after the edits) of the ones of yours that I have read. Great work!

### CODE REVIEW

**Comment by ofZach** [comment]
@arturoc @brannondorsey just checking in on this -- how do you want to proceed with this?

**Comment by brannondorsey** [comment]
This is still in an odd state of flux if I remember correctly. I can give
this chapter a thorough edit and PR ofBook master with my changes today.
How does that sound?

On Sun, Mar 22, 2015 at 9:23 AM, ofZach <notifications@github.com> wrote:

> @arturoc <https://github.com/arturoc> @brannondorsey
> <https://github.com/brannondorsey> just checking in on this -- how do you
> want to proceed with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/ofBook/pull/55#issuecomment-84617190>.
>



-- 
http://brannondorsey.com

**Comment by ofZach** [comment]
sounds good !!

**Comment by brannondorsey** [comment]
In the midst of this now and will push something by tonight. Because today is the final ofBook hack day would it be helpful if my note edits **[BD: like this]** were left in so that @arturoc has an opportunity to include or ignore them or should I simply incorporate my suggestions. @arturoc what do you think? Will you have time to make changes to this again soon once I push my changes in a couple of hours?

**Comment by brannondorsey** [comment]
@arturoc and @ofZach, I've completed my suggested edits to the Memory chapter and fixed merge conflicts. This PR is ready to be merged with master, however there are still many **[BD: comments]** that need to be addressed before this chapter should be considered finished. That said, most of my suggested edits can be run through fairly quickly. They are mainly for brief restructuring, sentence clarification, etc... I've made spelling/grammar edits inline.

**Comment by tpltnt** [comment]
Thank you for your edits.

**Comment by arturoc** [comment]
hey @tpltnt this wasn't correct, there was some fixes that overwrote previous corrections by myself. i'm going to revert this but please don't merge anything without the original author's permission

**Comment by bilderbuchi** [comment]
so, @tpltnt, now that you merged this PR, will you deal with the `[BD: ]` comments strewn throughout this PR, as mentioned in Brannon's last comment?

**Comment by tpltnt** [comment]
@arturoc thank you for pointing out my mistake. I did it because the corrections looked ok to me and I have not seen you changing anything. When do you think you will be done?

**Comment by arturoc** [comment]
no idea but please don't merge anything without the author's permission. 

@brannondorsey can you resend the PR? i don't think it can be done from here so you'll need to create a new one i think

**Comment by tpltnt** [comment]
@bilderbuchi yes, i was about to address them, but @arturoc seems to have taken up the work again.

**Comment by tpltnt** [comment]
@arturoc i pushed the branch "brannondorsey-pr55" which is the state of @brannondorsey master branch as used in his pull request. Will that work for you?

**Comment by arturoc** [comment]
mmh, i think it would be better to send a new PR but leave it like that by now.

**Comment by brannondorsey** [comment]
It seems like sending a new PR from my master branch won't work as those commits have now been committed and then reverted over. @arturoc how do you want to proceed with incorporating my edits into your chapter? These edits have been sitting here for a bit but they were up to date as of a month ago?

**Pull request merged**
