### PR TITLE
game_design chapter edit suggestions

### PR DESCRIPTION
**Pull request by synesthete**
Clean up minor typos and reformatting, rewording for increased clarity.

### CODE REVIEW

**Comment by ofZach** [comment]
@phoenixperry can you take a look at these changes, they seem good to me!

**Comment by bilderbuchi** [comment]
I'm not sure I agree with changing all the apostrophes from apostrophe characters `'` to this: `’`.

**Comment by synesthete** [comment]
The bulk of this chapter was with `’`. I normalized the beginning and end to match. 
Is there a preference one way or the other for standardizing this across the entirety of the book?

**Comment by ofZach** [comment]
I don't think we've ever standardized this, I'm fine with either, is there a reason not to use ’ (which is more typographically correct, I guess) ?

**Comment by bilderbuchi** [comment]
one reason: how do you enter this? at least my keyboard only has a typewrite apostrophe key, and no typographic apostrophe key.

**Comment by ofZach** [comment]
I've never looked into this, here's a couple of links: 

http://www.danandcheryl.com/2010/08/how-to-type-curly-quotes-in-mac-os-x
http://unix.stackexchange.com/questions/9867/how-to-type-smart-quotes-u201c-u201d

**Comment by bilderbuchi** [comment]
also, be aware that forward/backticks or prime characters are not the correct choices. whatever zach typed, from what i see, is a typhographic apostrophe. [WP reference](http://en.wikipedia.org/wiki/Apostrophe#Computing) if you enjoy nerding out on typography. :-P :D

**Comment by synesthete** [comment]
Generally I know my primes from forward/back ticks and typographic quotes. Inputting the typographic quotes is definitely more involved, but I think the payoff of a well-formatted document is worth the effort. I am happy to fix these up as I work my way through a complete read of the book. I can also circle back through the earlier chapters quickly.

**Comment by mikewesthad** [comment]
If I'm remembering correctly, the typographic quote within a code block will break the latex parsing (via listings package, #69).  I saw at least one example in the diff that might be a problem.

**Comment by bilderbuchi** [comment]
tbh, I think it's more appropriate to fix this automatically during conversion/compiling, cause otherwise we'll end up with another inconsistent bunch of edits. This book being envisioned as a living document, we'll also most probably get PRs using the typewriter apostrophes. 

Fwiw, for me personally (and as used in my chapter throughout), the typewriter apostrophes are the only practical option - it's a shift-key keystroke, where in contrast, I wouldn't even know how to enter a proper typographical apostrophe without consulting wikipedia et. al. I would guess that the majority of other contributors are in a similar situation. 
Interesting tidbit, on my laptop keyboard, the key glyph for the typewrite apostrophe (`shift-#` on a german layout) is a _typographical_ apostrophe. :-P

**Comment by ofZach** [comment]
I think @mikewesthad and @bilderbuchi make good points, I know the latex parsing has been quite rough when it hits things it doesn't like, so maybe it makes sense to (as a general rule) avoid those characters in the text and to add them via something like http://smartquotesjs.com/

**Comment by mikewesthad** [comment]
+1 to that

**Comment by ofZach** [comment]
ok here's a massive commit worth a solid look over -- I made a new branch to try to standardize this. 

https://github.com/openframeworks/ofBook/commit/fc3d75abf6bab4602d7c3559d8b85d9e6894e722

done via
     find . -type f -name '*.md' -exec sed -i '' s/’/\'/ {} +
     find . -type f -name '*.md' -exec sed -i '' s/‘/\'/ {} +

**Comment by mikewesthad** [comment]
@ofZach, nice!  Looks good to me.  Seems like a few slipped under the radar somehow (e.g. this [line](https://github.com/openframeworks/ofBook/commit/fc3d75abf6bab4602d7c3559d8b85d9e6894e722#diff-52cfbf77416bba4771dae6df7f0438ccR936))?  The game design chapter was written in word (or something similar), so maybe something special is going in this chapter.

Should we do the same for double quotes?  In skimming the commit, I saw that at least the installation_up_4evr_macosx chapter mixes " " and “ ” (with at least once case " ”).

**Comment by ofZach** [comment]
I think there's some catching issues maybe on the github diffs, as I think this is fixed.   if I do this: 

     grep '’' */*.md 
     grep '‘' */*.md

I'm not seeing anything.  happy to attack the double quotes :)

**Comment by ofZach** [comment]
ok pushed an attempt to rid of curly quotes

**Comment by phoenixperry** [comment]
I can sign off on these

**Comment by bilderbuchi** [comment]
wow, great effort, thanks!

**Pull request merged**
