### PR TITLE
Game Design updates

### PR DESCRIPTION
**Pull request by kaylalewis**

### CODE REVIEW

**Comment by ofZach** [comment]
@phoenixperry  can you take a look at these suggested edits?

**Comment by tpltnt** [comment]
ping @phoenixperry

**Comment by tpltnt** [comment]
@phoenixperry please take a look at the suggested changes until 2015-06-10. Otherwise I consider the work as abandoned and would take over.

**Comment by mikewesthad** [comment]
@tpltnt, I don't think @phoenixperry gets github notifications.  I emailed her about this PR a year ago on the mailing list, and she was happy to get the feedback.  It might be worth reaching to her over the mailing list again

**Comment by tpltnt** [comment]
@mikewesthad I wrote her an email about 3 hours ago. If I get no reply there i will try the mailing list. Thanks for the hint.

**Comment by tpltnt** [comment]
@kaylalewis thank you for your contribution.

**Pull request merged**
